spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.isiyi.share.entity
  global-config:
    refresh:  true
    db-config:
      id-type: auto
      field-strategy: ignored
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

